package detect

import (
	"path"
	"strings"
)

// Context describes where content came from, so the aggregator can discount
// findings that live in places secrets legitimately appear as illustrations.
//
// It carries no io.Reader and no file handle: callers classify a path with
// ClassifyPath and hand the result in.
type Context struct {
	Path string

	IsTest      bool
	IsDoc       bool
	IsExample   bool
	IsLockfile  bool
	IsGenerated bool
	IsVendored  bool
	IsMinified  bool
}

// Discounted reports whether this context should cost a finding one level of
// confidence.
func (c Context) Discounted() bool {
	return c.IsTest || c.IsDoc || c.IsExample || c.IsLockfile || c.IsGenerated || c.IsVendored || c.IsMinified
}

// Reason renders the discount as a short human-readable note.
func (c Context) Reason() string {
	switch {
	case c.IsExample:
		return "example/sample file"
	case c.IsDoc:
		return "documentation file"
	case c.IsTest:
		return "test file"
	case c.IsLockfile:
		return "lockfile"
	case c.IsVendored:
		return "vendored dependency"
	case c.IsGenerated:
		return "generated file"
	case c.IsMinified:
		return "minified file"
	default:
		return ""
	}
}

var (
	docExts = map[string]bool{
		".md": true, ".markdown": true, ".rst": true, ".adoc": true,
		".txt": true, ".mdx": true,
	}
	lockfiles = map[string]bool{
		"package-lock.json": true, "yarn.lock": true, "pnpm-lock.yaml": true,
		"go.sum": true, "cargo.lock": true, "poetry.lock": true,
		"composer.lock": true, "gemfile.lock": true, "pipfile.lock": true,
		"packages.lock.json": true, "bun.lockb": true, "flake.lock": true,
	}
	vendorDirs = []string{
		"vendor/", "node_modules/", "third_party/", "thirdparty/",
		".venv/", "site-packages/", "bower_components/",
	}
	// testNameMarkers are matched against the file name.
	testNameMarkers = []string{"_test.", ".test.", ".spec.", "test_", "_spec."}
	// testDirs are matched against whole path segments, so "test/foo" and
	// "a/testcerts/b" both count while "latest/foo" does not.
	testDirs = map[string]bool{
		"test": true, "tests": true, "testdata": true, "testing": true,
		"spec": true, "specs": true, "fixtures": true, "fixture": true,
		"mocks": true, "mock": true, "__tests__": true, "e2e": true,
		"testcerts": true, "testcert": true, "testfiles": true,
	}
	exampleNameMarkers = []string{".example", ".sample", ".template", ".dist"}
	exampleDirs        = map[string]bool{
		"example": true, "examples": true, "sample": true, "samples": true,
		"demo": true, "demos": true,
	}
	// A docs/ directory is documentation, whatever the file extension.
	docDirs = map[string]bool{"docs": true, "doc": true, "documentation": true}
)

// ClassifyPath derives a Context from a repository-relative path. Path
// classification is intentionally cheap and string-based: it runs once per
// file, never per line.
func ClassifyPath(p string) Context {
	c := Context{Path: p}
	lower := strings.ToLower(filepathSlash(p))
	base := path.Base(lower)
	ext := path.Ext(base)

	c.IsDoc = docExts[ext]
	c.IsLockfile = lockfiles[base]

	for _, d := range vendorDirs {
		if strings.Contains(lower, d) || strings.HasPrefix(lower, strings.TrimSuffix(d, "/")+"/") {
			c.IsVendored = true
			break
		}
	}
	for _, m := range testNameMarkers {
		if strings.Contains(base, m) {
			c.IsTest = true
			break
		}
	}
	for _, m := range exampleNameMarkers {
		if strings.Contains(base, m) {
			c.IsExample = true
			break
		}
	}
	// Directory markers are matched per path segment. Substring matching
	// would classify "latest/config" as a test and "godoc/x" as docs, and
	// would miss a leading "test/" for want of a slash in front of it.
	for _, seg := range strings.Split(path.Dir(lower), "/") {
		if testDirs[seg] {
			c.IsTest = true
		}
		if exampleDirs[seg] {
			c.IsExample = true
		}
		if docDirs[seg] {
			c.IsDoc = true
		}
		if seg == "dist" || seg == "build" {
			c.IsMinified = true
		}
	}
	if strings.Contains(base, ".min.") || strings.HasSuffix(base, ".map") {
		c.IsMinified = true
	}
	if strings.HasSuffix(base, ".pb.go") || strings.HasSuffix(base, "_generated.go") ||
		strings.HasSuffix(base, ".generated.go") || strings.HasSuffix(base, "_gen.go") ||
		strings.HasSuffix(base, ".designer.cs") {
		c.IsGenerated = true
	}
	return c
}

func filepathSlash(p string) string { return strings.ReplaceAll(p, "\\", "/") }

// GeneratedHeaderMarkers are the conventional "do not edit" banners. The
// scanner checks the first few lines of a file against them, which catches
// generated files whose names give nothing away.
var GeneratedHeaderMarkers = []string{
	"code generated by",
	"do not edit",
	"autogenerated",
	"auto-generated",
	"@generated",
	"generated by protoc",
}

// LooksGenerated reports whether a file header contains a generated-code
// banner.
func LooksGenerated(header string) bool {
	lower := strings.ToLower(header)
	for _, m := range GeneratedHeaderMarkers {
		if strings.Contains(lower, m) {
			return true
		}
	}
	return false
}
