package cli

import (
	"fmt"
	"io"
	"sort"
	"strings"
	"text/tabwriter"

	"github.com/spf13/cobra"

	"github.com/dotMuny/EnvLeak/internal/detect"
	"github.com/dotMuny/EnvLeak/internal/rules"
)

func newRulesCommand(streams IO, g *globalFlags) *cobra.Command {
	var (
		markdown bool
		tag      string
	)

	cmd := &cobra.Command{
		Use:   "rules",
		Short: "List the detection rules",
		Long: `List the rules in the active catalogue.

--markdown renders the reference table in docs/rules.md, so the documentation
is generated from the same YAML the scanner runs: "make docs".`,
		Example: `  envleak rules
  envleak rules --tag aws
  envleak rules --markdown > docs/rules.md`,
		Args: cobra.NoArgs,
		RunE: func(_ *cobra.Command, _ []string) error {
			rc, err := g.resolve(".", streams)
			if err != nil {
				return err
			}
			list := rc.catalogue.Rules
			if tag != "" {
				list = filterByTag(list, tag)
			}
			if markdown {
				return writeRulesMarkdown(streams.Out, list)
			}
			return writeRulesTable(streams.Out, list)
		},
	}

	cmd.Flags().BoolVar(&markdown, "markdown", false, "render docs/rules.md instead of a terminal table")
	cmd.Flags().StringVar(&tag, "tag", "", "only show rules carrying this tag")
	return cmd
}

func filterByTag(in []rules.Compiled, tag string) []rules.Compiled {
	var out []rules.Compiled
	for _, r := range in {
		for _, t := range r.Tags {
			if strings.EqualFold(t, tag) {
				out = append(out, r)
				break
			}
		}
	}
	return out
}

func writeRulesTable(w io.Writer, list []rules.Compiled) error {
	tw := tabwriter.NewWriter(w, 0, 4, 2, ' ', 0)
	if _, err := fmt.Fprintln(tw, "ID\tSEVERITY\tCONFIDENCE\tVALIDATOR\tENTROPY\tDESCRIPTION"); err != nil {
		return wrapErr(err)
	}
	for _, r := range list {
		entropy := "-"
		if r.EntropyThreshold > 0 {
			entropy = fmt.Sprintf("%.1f", r.EntropyThreshold)
		}
		validator := r.Validator
		if validator == "" {
			validator = "-"
		}
		if _, err := fmt.Fprintf(tw, "%s\t%s\t%s\t%s\t%s\t%s\n",
			r.ID, r.Severity, r.Confidence, validator, entropy, r.Description); err != nil {
			return wrapErr(err)
		}
	}
	if _, err := fmt.Fprintf(tw, "\n%d rules\n", len(list)); err != nil {
		return wrapErr(err)
	}
	return wrapErr(tw.Flush())
}

func writeRulesMarkdown(w io.Writer, list []rules.Compiled) error {
	var b strings.Builder

	b.WriteString("# Rule catalogue\n\n")
	b.WriteString("<!-- Generated by `envleak rules --markdown`. Do not edit by hand; edit\n")
	b.WriteString("     internal/rules/rules.yaml and run `make docs`. -->\n\n")
	fmt.Fprintf(&b, "%d rules, grouped by tag. Every rule below is covered by at least one\n", len(list))
	b.WriteString("positive and one negative test case, taken from the examples in this file.\n\n")

	b.WriteString("## Confidence\n\n")
	b.WriteString("A finding's confidence is derived from which engines agreed:\n\n")
	b.WriteString("| Situation | Confidence |\n|---|---|\n")
	b.WriteString("| Pattern hit on a prefix-anchored format, checksum validated | `high` |\n")
	b.WriteString("| Pattern hit on a prefix-anchored format, no validator | `high` |\n")
	b.WriteString("| Pattern hit whose entropy check passed | one level up from the rule's base |\n")
	b.WriteString("| Pattern hit whose entropy check failed | one level down |\n")
	b.WriteString("| Pattern hit whose checksum failed | one level down (never dropped) |\n")
	b.WriteString("| Found in a test, doc, example, lockfile or generated file | one level down |\n")
	b.WriteString("| Entropy engine alone, no pattern | `low` |\n\n")

	b.WriteString("## Validators\n\n")
	names := detect.ValidatorNames()
	sort.Strings(names)
	b.WriteString("| Validator | What it checks |\n|---|---|\n")
	for _, n := range names {
		b.WriteString("| `" + n + "` | " + validatorDoc(n) + " |\n")
	}
	b.WriteString("\n")

	b.WriteString("## Continuation checks\n\n")
	b.WriteString("Some matches only mean something in the light of the *next* line. A rule\n")
	b.WriteString("declaring a `continuation` has its match held back one line and dropped if\n")
	b.WriteString("the check fails, which is how a PEM banner quoted in a README stays quiet\n")
	b.WriteString("while the same banner followed by base64 does not.\n\n")
	cnames := detect.ContinuationNames()
	sort.Strings(cnames)
	b.WriteString("| Check | What it requires of the following line |\n|---|---|\n")
	for _, n := range cnames {
		b.WriteString("| `" + n + "` | " + continuationDoc(n) + " |\n")
	}
	b.WriteString("\n")

	byTag := map[string][]rules.Compiled{}
	for _, r := range list {
		tag := "other"
		if len(r.Tags) > 0 {
			tag = r.Tags[0]
		}
		byTag[tag] = append(byTag[tag], r)
	}
	tags := make([]string, 0, len(byTag))
	for t := range byTag {
		tags = append(tags, t)
	}
	sort.Strings(tags)

	b.WriteString("## Rules\n\n")
	for _, tag := range tags {
		fmt.Fprintf(&b, "### %s\n\n", tag)
		b.WriteString("| ID | Severity | Confidence | Validator / continuation | Entropy | Description |\n")
		b.WriteString("|---|---|---|---|---|---|\n")
		for _, r := range byTag[tag] {
			entropy, validator := "—", "—"
			if r.EntropyThreshold > 0 {
				entropy = fmt.Sprintf("%.1f", r.EntropyThreshold)
			}
			if r.Validator != "" {
				validator = "`" + r.Validator + "`"
			}
			if r.Continuation != "" {
				validator += " + `" + r.Continuation + "`"
			}
			fmt.Fprintf(&b, "| `%s` | %s | %s | %s | %s | %s |\n",
				r.ID, r.Severity, r.Confidence, validator, entropy, r.Description)
		}
		b.WriteString("\n")
	}

	b.WriteString("## Adding a rule\n\n")
	b.WriteString("1. Add an entry to `internal/rules/rules.yaml`.\n")
	b.WriteString("2. Give it at least one `positive` and one `negative` example — `TestRuleExamples`\n")
	b.WriteString("   enforces both, so a rule that does not work cannot be merged.\n")
	b.WriteString("3. Pick `keywords` that appear in every real match: the Aho-Corasick prefilter\n")
	b.WriteString("   only runs your regex on lines containing one of them.\n")
	b.WriteString("4. Run `make test docs`.\n")

	_, err := io.WriteString(w, b.String())
	return wrapErr(err)
}

func validatorDoc(name string) string {
	switch name {
	case "github-crc32":
		return "Recomputes the base62 CRC32 checksum in the last 6 characters of a prefixed GitHub token (`ghp_`, `gho_`, `ghu_`, `ghs_`, `ghr_`) over the preceding 30."
	case "github-pat-structure":
		return "Verifies the shape of a fine-grained PAT: `github_pat_` + 22 base62 + `_` + 59 base62. GitHub publishes no checksum for this format."
	case "jwt":
		return "Base64url-decodes the first segment and requires valid JSON carrying a non-empty `alg` claim, which rejects unrelated blobs that merely start with `eyJ`."
	default:
		return ""
	}
}

func continuationDoc(name string) string {
	switch name {
	case "pem-body":
		return "Base64 key material (at least 32 characters) or an RFC 1421 header such as `Proc-Type:`. A banner at end of file, or followed by prose, is dropped."
	default:
		return ""
	}
}

func wrapErr(err error) error {
	if err != nil {
		return fmt.Errorf("write rules: %w", err)
	}
	return nil
}
